amazonProperties:
  accessKey: ''
  bucketName: ''
  region: ''
  secretKey: ''


spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/sbms39
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
